id: P4464A6F8
initial_creation_type: input
source_metadata:
  Title: Madhyamakaśāstra of Nāgārjuna
  Editor: Vaidya, P. L.
  Publisher: The Mithila Institute of Post-Graduate Studies and Research in Sanskrit
    Learning
  Place of Publication: Darbhanga
  Year: '1960'
  Vigrahavyāvartanī:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:41:13.465325'
last_modified_at: '2022-03-08T16:41:13.465333'
